name: Kodezi CLI test

permissions: write-all

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout new branch
        run: |
            git checkout -b kodezi-patch-${{github.run_number}}

      - uses: actions/setup-node@v3
        with:
            node-version: "16.x"
            registry-url: "https://registry.npmjs.org"

      - name: kodezi cli test
        run : |
          npm i -g kodezi-cli
          kodezi
          kodezi --cloud -l "java"  -f "documentation,debugging" -file ./java_testcases  --email "marcusdias@yopmail.com" --token "kdz_rkLjquAquXvqolwSvJXWbd"  --out ./kodezimode

      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Push Code
        run: |
          git add .
          git commit -m "a new test from cli."
          git push origin kodezi-patch-${{github.run_number}}
